const MenuOptions = {
  tea: {
    name: "tea",
    displayName: "Tea",
    price: 0.8,
    amount: 0,
    menuOption: true,
  },
  coffee: {
    name: "coffee",
    displayName: "Coffee",
    price: 0.9,
    amount: 0,
    menuOption: true,
  },
  hotChocolate: {
    name: "hotChocolate",
    displayName: "Hot Chocolate",
    price: 1.0,
    amount: 0,
    menuOption: true,
  },
  cola: {
    name: "cola",
    displayName: "Coca Cola",
    price: 0.7,
    amount: 0,
    menuOption: true,
  },
  sprite: {
    name: "sprite",
    displayName: "Sprite",
    price: 0.7,
    amount: 0,
    menuOption: true,
  },
  vimto: {
    name: "vimto",
    displayName: "Vimto",
    price: 0.7,
    amount: 0,
    menuOption: true,
  },
  water1: {
    name: "water1",
    displayName: "Water (500ml)",
    price: 0.5,
    amount: 0,
    menuOption: true,
  },
  water2: {
    name: "water2",
    displayName: "Water (1L)",
    price: 0.8,
    amount: 0,
    menuOption: true,
  },
  flapJack: {
    name: "flapJack",
    displayName: "Flap Jack",
    price: 0.75,
    amount: 0,
    menuOption: true,
  },
  brownie: {
    name: "brownie",
    displayName: "Choc. Brownie",
    price: 0.9,
    amount: 0,
    menuOption: true,
  },
  teaCake: {
    name: "teaCake",
    displayName: "Tea Cake,",
    price: 0.5,
    amount: 0,
    menuOption: true,
  },
  bread: {
    name: "bread",
    price: 0.8,
    amount: 0,
    menuOption: false,
  },
  toasted: {
    name: "toasted",
    price: 0.5,
    amount: 0,
    menuOption: false,
  },
  meat: {
    name: "meat",
    price: 1.5,
    amount: 0,
    menuOption: false,
  },
  ingredients: {
    name: "ingredients",
    price: 0.7,
    amount: 0,
    menuOption: false,
  },
  garnish: {
    name: "garnish",
    price: 0.6,
    amount: 0,
    menuOption: false,
  },
};

export default MenuOptions;
